
-- -----------------------------------------------------
-- Table RAZA
-- -----------------------------------------------------
DROP TABLE RAZA;
CREATE TABLE RAZA (
  ID_RAZA INT NOT NULL,
  NOMBRE VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID_RAZA));

-- -----------------------------------------------------
-- Table ESTADO_MASCOTA
-- -----------------------------------------------------
DROP TABLE ESTADO_MASCOTA;
CREATE TABLE ESTADO_MASCOTA (
  ID_ESTADO_MASCOTA INT NOT NULL,
  NOMBRE VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID_ESTADO_MASCOTA));


-- -----------------------------------------------------
-- Table TIPO_MASCOTA
-- -----------------------------------------------------
DROP TABLE TIPO_MASCOTA;
CREATE TABLE TIPO_MASCOTA (
  ID_TIPO_MASCOTA INT NOT NULL,
  NOMBRE VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID_TIPO_MASCOTA));

-- -----------------------------------------------------
-- Table MASCOTA
-- -----------------------------------------------------
DROP TABLE MASCOTA;
CREATE TABLE MASCOTA (
  ID_MASCOTA INT NOT NULL,
  ID_RAZA INT NOT NULL,
  NOMBRE VARCHAR(45) NULL,
  EDAD INT NOT NULL,
  ID_ESTADO_MASCOTA INT NOT NULL,
  ID_TIPO_MASCOTA INT NOT NULL,
  OTRA_RAZA VARCHAR(45) NULL,
  OTRO_TIPO_MASCOTA VARCHAR(45) NULL,
  PRIMARY KEY (ID_MASCOTA), 
  CONSTRAINT fk_MASCOTA_RAZA
    FOREIGN KEY (ID_RAZA)
    REFERENCES RAZA (ID_RAZA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_MASCOTA_ESTADO_MASCOTA1
    FOREIGN KEY (ID_ESTADO_MASCOTA)
    REFERENCES ESTADO_MASCOTA (ID_ESTADO_MASCOTA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_MASCOTA_TIPO_MASCOTA1
    FOREIGN KEY (ID_TIPO_MASCOTA)
    REFERENCES TIPO_MASCOTA (ID_TIPO_MASCOTA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table TIPO_USUARIO
-- -----------------------------------------------------
DROP TABLE TIPO_USUARIO;
CREATE TABLE TIPO_USUARIO (
  ID_TIPO_USUARIO SERIAL NOT NULL ,
  NOMBRE VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID_TIPO_USUARIO));


-- -----------------------------------------------------
-- Table USUARIO
-- -----------------------------------------------------
DROP TABLE USUARIO;
CREATE TABLE USUARIO (
  ID_USUARIO SERIAL NOT NULL ,
  NOMBRES VARCHAR(45) NOT NULL,
  APELLIDOS VARCHAR(45) NOT NULL,
  EMAIL VARCHAR(45) NOT NULL,
  PASSWORD VARCHAR(45) NOT NULL,
  DIRECCION VARCHAR(45) NOT NULL,
  TELEFONO1 VARCHAR(15) NOT NULL,
  TELEFONO2 VARCHAR(15) NULL,
  ID_TIPO_USUARIO INT NOT NULL,
  PRIMARY KEY (ID_USUARIO),
  CONSTRAINT fk_USUARIO_TIPO_USUARIO1
    FOREIGN KEY (ID_TIPO_USUARIO)
    REFERENCES TIPO_USUARIO (ID_TIPO_USUARIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table ID_ESTADO_SOLICITUD
-- -----------------------------------------------------
DROP TABLE ID_ESTADO_SOLICITUD;
CREATE TABLE ID_ESTADO_SOLICITUD (
  ID_ESTADO_SOLICITUD INT NOT NULL,
  NOMBRE VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID_ESTADO_SOLICITUD));



-- -----------------------------------------------------
-- Table SOLICITUD
-- -----------------------------------------------------
DROP TABLE SOLICITUD;
CREATE TABLE SOLICITUD (
  ID_SOLICITUD SERIAL NOT NULL ,
  ID_MASCOTA INT NOT NULL,
  ID_USUARIO INT NOT NULL,
  ID_ESTADO_SOLICITUD INT NOT NULL,
  FECHA_SOLICITUD DATE NOT NULL,
  PRIMARY KEY (ID_SOLICITUD), 
  CONSTRAINT fk_SOLICITUD_MASCOTA1
    FOREIGN KEY (ID_MASCOTA)
    REFERENCES MASCOTA (ID_MASCOTA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_SOLICITUD_USUARIO1
    FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO (ID_USUARIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_SOLICITUD_ID_ESTADO_SOLICITUD1
    FOREIGN KEY (ID_ESTADO_SOLICITUD)
    REFERENCES ID_ESTADO_SOLICITUD (ID_ESTADO_SOLICITUD)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


INSERT INTO RAZA VALUES (1,'raza1');
INSERT INTO RAZA VALUES (2,'raza2');
INSERT INTO RAZA VALUES (3,'raza3');

INSERT INTO TIPO_MASCOTA VALUES (1,'tipo1');
INSERT INTO TIPO_MASCOTA VALUES (2,'tipo2');
INSERT INTO TIPO_MASCOTA VALUES (3,'tipo3');




INSERT INTO estado_mascota VALUES (1,'estado1');
INSERT INTO estado_mascota VALUES (2,'estado2');
INSERT INTO estado_mascota VALUES (3,'estado3');


INSERT INTO mascota VALUES (1,1,'mascota',1,1,1,'1','1');


INSERT INTO TIPO_USUARIO VALUES (1,'ADMIN');
INSERT INTO TIPO_USUARIO VALUES (2,'USUARIO');

INSERT  INTO USUARIO VALUES (1,'admin_2','super_2','admin@correo.com','admin','CR 70D #79-74',1234567,9876543,1);